create table INSTRUMENTOS
(
PID varchar(3) not null,
TIPO varchar(25) not null,
MODELO varchar(50) not null,
COR varchar(50),
MARCA varchar(25) not null,
PRECO decimal(6,2) not null,
primary key(PID));

insert into INSTRUMENTOS values ('001','GUITARRA','SG SPECIAL FADED WORN CHERRY','VINHO (WORN CHERRY) (WC)','GIBSON',5599.00);
insert into INSTRUMENTOS values ('002','GUITARRA','SG FADED 2016 T','MARROM (WORN BROWN) (WB)','GIBSON',8989.00);
insert into INSTRUMENTOS values ('003','GUITARRA','SG FADED 2016 T','VINHO (WORN CHERRY) (WC)','GIBSON',8989.00);
insert into INSTRUMENTOS values ('004','GUITARRA','SG STANDARD 2014 MIN-ETUNE','MARROM (WALNUT) (592)','GIBSON',9229.00);
insert into INSTRUMENTOS values ('005','GUITARRA','LES PAUL 50S TRIBUTE 2016 T','PRETO (SATIN EBONY) (SE)','GIBSON',9549.00);

drop table INSTRUMENTOS;

select * from INSTRUMENTOS;

/*
TIPO        MODELO                          COR                         MARCA	  PRECO
GUITARRA    SG SPECIAL FADED WORN CHERRY    VINHO (WORN CHERRY) (WC)	  GIBSON	5599,00
GUITARRA    SG FADED 2016 T                 MARROM (WORN BROWN) (WB)	  GIBSON	8989,00
GUITARRA    SG FADED 2016 T                 VINHO (WORN CHERRY) (WC)	  GIBSON	8989,00
GUITARRA    SG STANDARD 2014 MIN-ETUNE      MARROM (WALNUT) (592)	      GIBSON	9229,00
GUITARRA    LES PAUL 50S TRIBUTE 2016 T     PRETO (SATIN EBONY) (SE)	  GIBSON	9549,00
*/
